#Install all most used packages

install.packages("car")
install.packages("gdata")
install.packages("Hmisc")
install.packages("metafor")
install.packages("plyr")
install.packages("ggplot2")
install.packages("gridExtra")
install.packages("psych") 
install.packages("RCurl")
install.packages("irr") 
install.packages("nortest") 
install.packages("moments")
install.packages("GPArotation")
install.packages("nFactors")
install.packages("meta")
install.packages("qgraph")
install.packages("reshape")
install.packages("repmis")
install.packages("ltm")
install.packages("gmodels")
install.packages("eRm")
install.packages("mirt")
install.packages("IsingSampler")
install.packages("IsingFit")
install.packages("xml2")
install.packages("rversions")
install.packages("devtools")
install.packages("rgdal")
install.packages("rgeos")
install.packages("sqldf")
install.packages("pgirmess")
install.packages("VIM")
install.packages("caret")
install.packages("wordcloud")

devtools::install_github("jennybc/googlesheets")
devtools::install_github("cran/epicalc")
devtools::install_github("BioStatMatt/sas7bdat")
devtools::install_github("rdpeng/gpclib")

source("http://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")
biocLite("RGBL")