CREATE DATABASE IF NOT EXISTS automapsus 
  CHARACTER SET = 'UTF8'
  COLLATE = 'utf8_general_ci';
USE automapsus;
CREATE TABLE observations
(
    id int NOT NULL AUTO_INCREMENT,
    nome varchar(1000),
    cod_cnes_unidade varchar(1000),
    microarea varchar(1000),
    numero_cartao_sus varchar(255),
    data_nascimento date,
    idade int,
    sexo varchar(255),
    gestante varchar(20),
    raca_cor varchar(255),
    nome_completo_mae varchar(1000),
    nacionalidade varchar(1000),
    estado_civil varchar(255),
    grau_escolaridade varchar(255),
    ocupacao varchar(1000),
    crianca varchar(20),
    crianca_cuidador varchar(1000),
    cuidador varchar(20),
    plano_de_saude varchar(20),
    informar_orientacao varchar(20),
    orientacao_sexual varchar(20),
    deficiencia varchar(20),
    peso varchar(255),
    peso_kg int,
    altura_cm int,
    imc varchar(255),
    ca_cm int,
    pa_mmhg int,
    glicemia int,
    fumante varchar(20),
    alcool varchar(20),
    drogas varchar(20),
    hipertensao varchar(20),
    remedio_hipertensao varchar(20),
    diabetes varchar(20),
    remedio_diabetes varchar(20),
    colesterol_alto varchar(20),
    remedio_colesterol varchar(20),
    avc_derrame varchar(20),
    infarto varchar(20),
    doenca_cardiaca  varchar(255),
    doenca_renal varchar(255),
    doenca_respiratoria varchar(255),
    hanseniase varchar(20),
    tuberculose varchar(20),
    cancer varchar(20),
    internacao varchar(20),
    saude_mental varchar(20),
    acamado varchar(20),
    plantas_medicinais varchar(20),
    moradia varchar(255),
    localizacao_urbana varchar(20),
    domicilio varchar(255),
    acesso_domicilio varchar(255),
    construcao_domicilio  varchar(255),
    abastecimento_agua varchar(255),
    tratamento_agua varchar(255),
    esgoto varchar(255),
    lixo varchar(255),
    animais varchar(255),
    doenca_procura varchar(255),
    comunicacao varchar(255),
    participacao_grupos varchar(255),
    transporte varchar(255),
    bolsa_familia varchar(20),
    cad_unico varchar(20),
    familia_acamado varchar(20),
    deficiencia_fisica varchar(20),
    deficiencia_mental varchar(20),
    saneamento varchar(20),
    desnutricao_grave varchar(20),
    drogadicao varchar(20),
    desemprego varchar(20),
    analfabetismo varchar(20),
    menor_6_anos varchar(20),
    maior_70_anos varchar(20),
    has varchar(20),
    dm varchar(20),
    numero_moradores int,
    numero_comodos int,
    endereco varchar(2000),
    lat varchar(30),
    lon varchar(30),
    PRIMARY KEY (id)
);

CREATE TABLE admin
(
    id int NOT NULL AUTO_INCREMENT,
    username varchar(255),
    password varchar(255),
    PRIMARY KEY (id)
);